### ISSUE TITLE
It's possible to extract all frames (one by one) from a video

### ISSUE THREAD

**Issue by Mouadabdelghafouraitali** [HMS-Core/hms-video-editor-demo#7]
Hi, is there any way to extract frames from a video (frame by frame) ?

**Comment by Mike-mei** [comment]
Why do you want to achieve that? What's the specific application scenario?
Please also provide your appid.

**Comment by Mouadabdelghafouraitali** [comment]
@Mike-mei thank you for your comment, well, right now, I'm using **[Huawei Image Segmentation](https://developer.huawei.com/consumer/en/doc/development/hiai-Guides/image-segmentation-0000001050040109)** since it support image only, I would like to extract video frames, so I can remove the background from the  video too.
